# Praktikum Pertemuan 3 — Menyiapkan Data Proyek agar Layak dan Aman Dianalisis

**Mata Kuliah:** Exploratory Data Analysis (KMTI21133) — Pertemuan 3  
**Fase PjBL:** Perencanaan  
**Sub-CPMK3:** Mahasiswa mampu merumuskan pertanyaan analisis dari masalah nyata serta memperoleh data
sesuai lisensi sumbernya, serta mengidentifikasi dan menangani data pribadi yang terkandung di dalamnya (C4, A3).

**Cara kerja.** Sel bertanda `# TODO` Anda kerjakan sendiri; setiap TODO disertai *expected output* agar Anda bisa memeriksa jawaban sendiri. Sel Markdown bertanda **Jawaban Anda** diisi dengan tulisan, bukan kode.

**Bagian A–F** dikerjakan di kelas dengan dataset latihan. **Bagian G** dikerjakan bersama tim di luar kelas dengan dataset proyek Anda sendiri, dan hasilnya menjadi isi **M1 (bobot 5%)** yang dikumpulkan sesuai tenggat di LMS.

## Bagian 0 — Persiapan

Dataset latihan: **`peserta_pelatihan_umkm_2025.csv`** — 620 baris, 28 kolom.
Data pendaftaran dan hasil pelatihan UMKM binaan kampus.

> **Catatan penting:** seluruh isi dataset ini **sintetis** dan dibuat untuk latihan. Tidak ada orang nyata di dalamnya.
> Nomor NIK, nomor telepon, dan surel sengaja dibuat dengan pola yang tidak valid. Perlakukan tetap seolah-olah data nyata,
> karena itulah kebiasaan yang sedang kita latih.

In [ ]:
import pandas as pd
import numpy as np
import hashlib, os

pd.set_option('display.max_columns', 40)
pd.set_option('display.width', 140)
print('pandas', pd.__version__)

pandas 2.2.3

In [ ]:
FILE = 'peserta_pelatihan_umkm_2025.csv'

if not os.path.exists(FILE):
    try:
        from google.colab import files
        files.upload()          # pilih peserta_pelatihan_umkm_2025.csv
    except ImportError:
        raise FileNotFoundError('Letakkan CSV di folder yang sama dengan notebook ini.')

df = pd.read_csv(FILE)
print(df.shape)
df.head(3)

Saving peserta_pelatihan_umkm_2025.csv to peserta_pelatihan_umkm_2025.csv
(620, 28)

,id_peserta,nama_lengkap,nik_dummy,no_hp,email,alamat_jalan,kelurahan,kecamatan,kota,tanggal_lahir,jenis_kelamin,pendidikan_terakhir,status_disabilitas,jumlah_anak,penghasilan_pribadi_bulanan,nama_usaha,kategori_usaha,produk_utama,lama_usaha_tahun,jumlah_karyawan,omzet_usaha_bulanan,pernah_ikut_pelatihan,kanal_pendaftaran,tanggal_daftar,kehadiran_persen,skor_prates,skor_pascates,tingkat_kepuasan
0,PLT-2025-1309,Ratna Hidayat,99991405899249,8.000426e+10,ratna.hidayat@contoh.example,Jl. Cempaka No. 106 RT 02/RW 10,Sukatani,Tapos,Depok,1989-05-14,P,SMP,Tidak,3,500000,CV Mandiri Jaya,Kuliner,Roti dan kue,12.8,4,2950000,Tidak,Datang langsung,2025-04-04,75,52,67.0,5.0
1,PLT-2025-1512,Bunga Santoso,99992410874363,8.000347e+10,bunga.santoso@contoh.example,Jl. Bougenville No. 80 RT 10/RW 02,Mampang,Pancoran Mas,Depok,1987-10-24,P,D3,Tidak,1,950000,Dapur Cahaya Abadi,Jasa Digital,Servis gawai,6.5,3,7750000,Tidak,Formulir daring,2025-02-02,70,59,75.0,4.9
2,PLT-2025-1360,Endah Ramadhan,99991107987303,8.000266e+10,endah.ramadhan@contoh.example,Jl. Anggrek No. 138 RT 07/RW 08,Limo,Limo,Depok,1998-07-11,P,D3,Tidak,2,1500000,Griya Harum Makmur,Kuliner,Katering rumahan,2.5,0,7550000,Tidak,WhatsApp,2025-03-26,90,51,61.0,4.9

---
## Bagian A — Merumuskan pertanyaan analisis

Sebuah pertanyaan analisis dianggap layak bila lolos **tiga uji**:

1. **Uji kolom** — kolom mana yang akan menjawabnya?
2. **Uji bentuk jawaban** — jawabannya berupa angka, peringkat, perbandingan, atau sebaran?
3. **Uji tindak lanjut** — kalau terjawab, apa yang bisa diputuskan?

In [ ]:
# TODO A1 — kenali kolom yang tersedia sebelum menulis pertanyaan
# a. Cetak daftar nama kolom beserta tipe datanya
# b. Cetak jumlah baris dan kolom
# Expected: 620 baris x 28 kolom

#Jawaban :
# a
df.info()
# b
print(df.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31822 entries, 0 to 31821
Data columns (total 38 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Date                         31822 non-null  datetime64[ns]
 1   Location ISO Code            31822 non-null  object
 2   Location                     31822 non-null  object
 3   New Cases                    31822 non-null  int64
 4   New Deaths                   31822 non-null  int64
 5   New Recovered                31822 non-null  int64
 6   New Active Cases             31822 non-null  int64
 7   Total Cases                  31822 non-null  int64
 8   Total Deaths                 31822 non-null  int64
 9   Total Recovered              31822 non-null  int64
 10  Total Active Cases           31822 non-null  int64
 11  Location Level               31822 non-null  object
 12  City or Regency              0 non-null      float64
 13  Province                     30893 non-null  object
 14  Country                      31822 non-null  object
 15  Continent                    31822 non-null  object
 16  Island                       30893 non-null  object
 17  Time Zone                    30893 non-null  object
 18  Special Status               4558 non-null   object
 19  Total Regencies              31822 non-null  int64
 20  Total Cities                 30921 non-null  float64
 21  Total Districts              31822 non-null  int64
 22  Total Urban Villages         30918 non-null  float64
 23  Total Rural Villages         30893 non-null  float64
 24  Area (km2)                   31822 non-null  int64
 25  Population                   31822 non-null  int64
 26  Population Density           31822 non-null  float64
 27  Longitude                    31822 non-null  float64
 28  Latitude                     31822 non-null  float64
 29  New Cases per Million        31822 non-null  float64
 30  Total Cases per Million      31822 non-null  float64
 31  New Deaths per Million       31822 non-null  float64
 32  Total Deaths per Million     31822 non-null  float64
 33  Total Deaths per 100rb       31822 non-null  float64
 34  Case Fatality Rate           31822 non-null  object
 35  Case Recovered Rate          31822 non-null  object
 36  Growth Factor of New Cases   29883 non-null  float64
 37  Growth Factor of New Deaths  28375 non-null  float64
dtypes: datetime64[ns](1), float64(14), int64(12), object(11)
memory usage: 9.2+ MB
(31822, 38)

### TODO A2 — perbaiki tiga pertanyaan berikut

Tulis versi perbaikannya di sel di bawah, beserta kolom yang akan dipakai.

| No | Draf pertanyaan | Masalahnya |
|---|---|---|
| 1 | Bagaimana kondisi peserta pelatihan? | Terlalu kabur |
| 2 | Apakah peserta yang lebih kaya lebih sukses? | "Kaya" dan "sukses" belum didefinisikan sebagai kolom |
| 3 | Apakah pelatihan menaikkan omzet peserta? | Uji kolom gagal — cek sendiri mengapa |

**Jawaban Anda:**

1. Perbaikan: _(Bagaimana sebaran/distribusi tingkat pendidikan terakhir peserta pelatihan?)_ — Kolom: _(pendidikan)_
2. Perbaikan: _(Apakah peserta dengan omzet awal lebih tinggi memiliki nilai post-test / skor evaluasi yang lebih tinggi?)_ — Kolom: _(tulis di sini)_
3. Mengapa uji kolom gagal: _(Uji kolom gagal karena dataset tidak menyediakan kolom omzet setelah/sesudah pelatihan. Data yang tersedia hanya mencatat omzet saat mendaftar/sebelum pelatihan, sehingga perubahan kenaikan omzet tidak dapat diukur.)_

In [ ]:
# TODO A3 — buktikan jawaban nomor 3 dengan kode
# Periksa apakah ada kolom omzet SESUDAH pelatihan di dataset ini.
# Petunjuk: cari nama kolom yang memuat kata 'omzet'
# Expected: hanya ada satu kolom omzet, yaitu omzet saat mendaftar
df.filter(like='omzet').columns

Index(['omzet_usaha_bulanan'], dtype='object')

---
## Bagian B — Skala pengukuran

### TODO B1 — klasifikasikan delapan kolom berikut

Isi tabel di sel Markdown ini. Pilihan: **nominal · ordinal · interval · rasio**.

| Kolom | Skala | Alasan singkat |
|---|---|---|
| `kategori_usaha` |nominal| Data kategori label/nama tanpa tingkatan atau urutan alami.|
| `pendidikan_terakhir` |ordinal|Memiliki tingkatan berurutan (SD < SMP < SMA < D3 < S1 < S2), namun jarak antar tingkat tidak terukur pasti.|
| `skor_prates` |interval|Nilai tes memiliki interval terukur, tetapi nilai 0 tidak berarti ketiadaan pengetahuan secara mutlak (tidak memiliki nol mutlak).|
| `omzet_usaha_bulanan` |rasio|Data numerik dengan nol mutlak (Rp0 berarti tidak ada pemasukan) dan operasi perkalian/pembagian bermakna.|
| `jumlah_karyawan` |rasio|Data pencacahan (count) dengan nol mutlak (0 orang berarti tidak ada karyawan).|
| `tingkat_kepuasan` |ordinal|Berupa skala persepsi berurutan (misal: Kurang < Cukup < Puas), jarak antar nilai tidak eksak.|
| `tanggal_daftar` |interval|Satuan waktu kalender memiliki interval yang konsisten (hari/bulan), namun tahun 0 tidak berarti ketiadaan waktu secara mutlak.|
| `kecamatan` |nominal|Data wilayah/nama tempat tanpa peringkat hierarkis.|

In [ ]:
# TODO B2 — perbaiki satu kolom ordinal yang salah tipe
import pandas as pd

# a. Jadikan 'pendidikan_terakhir' bertipe kategori berurutan
kategori_pendidikan = ['SD', 'SMP', 'SMA/SMK', 'D3', 'S1', 'S2'] #[cite: 3]
df['pendidikan_terakhir'] = pd.Categorical(
    df['pendidikan_terakhir'],
    categories=kategori_pendidikan,
    ordered=True
)

# b. Tampilkan value_counts() yang sudah urut menurut jenjang (bukan abjad)
print(df['pendidikan_terakhir'].value_counts().sort_index())

# c. Cetak median jenjang pendidikan lewat .cat.codes
median_code = int(df['pendidikan_terakhir'].cat.codes.median())
median_label = kategori_pendidikan[median_code]
print(f"median = {median_label}")

pendidikan_terakhir
SD          24
SMP         71
SMA/SMK    281
D3         107
S1         124
S2          13
Name: count, dtype: int64
median = SMA/SMK

In [ ]:
# TODO B3 — ubah dua kolom tanggal menjadi bertipe datetime
# Kolom: tanggal_lahir dan tanggal_daftar
df['tanggal_lahir'] = pd.to_datetime(df['tanggal_lahir'])
df['tanggal_daftar'] = pd.to_datetime(df['tanggal_daftar'])

# Lalu cetak tanggal pendaftaran paling awal dan paling akhir
tgl_awal = df['tanggal_daftar'].min()
tgl_akhir = df['tanggal_daftar'].max()

print("Tanggal pendaftaran paling awal:", tgl_awal)
print("Tanggal pendaftaran paling akhir:", tgl_akhir)

Tanggal pendaftaran paling awal: 2025-02-01 00:00:00
Tanggal pendaftaran paling akhir: 2025-05-31 00:00:00

---
## Bagian C — Kamus data

Kamus data adalah satu baris penjelasan untuk setiap kolom. Bangkitkan kerangkanya dengan kode, isi maknanya sendiri.

In [ ]:
# TODO C1 — bangkitkan kerangka kamus data
import pandas as pd

# Buat DataFrame bernama 'kamus'
kamus = pd.DataFrame({
    'nama_kolom': df.columns,
    'tipe_data': [df[col].dtype for col in df.columns],
    'nilai_unik': [df[col].nunique() for col in df.columns],
    'nilai_kosong': [df[col].isna().sum() for col in df.columns],
    'contoh_nilai': [df[col].dropna().iloc[0] if not df[col].dropna().empty else None for col in df.columns]
})

# Tambahkan empat kolom kosong yang akan diisi manual
kolom_manual = ['deskripsi', 'skala_pengukuran', 'kategori_data_pribadi', 'tindakan_penanganan']
for col in kolom_manual:
    kamus[col] = None

# Tampilkan informasi bentuk (Expected: 28 baris x 9 kolom)
print(kamus.shape)
kamus.head()

(28, 9)

,nama_kolom,tipe_data,nilai_unik,nilai_kosong,contoh_nilai,deskripsi,skala_pengukuran,kategori_data_pribadi,tindakan_penanganan
0,id_peserta,object,620,0,PLT-2025-1309,None,None,None,None
1,nama_lengkap,object,450,0,Ratna Hidayat,None,None,None,None
2,nik_dummy,int64,620,0,99991405899249,None,None,None,None
3,no_hp,float64,611,9,80004260813.0,None,None,None,None
4,email,object,450,0,ratna.hidayat@contoh.example,None,None,None,None

In [ ]:
# TODO C2 — kolom mana yang punya nilai kosong?
# Tampilkan hanya baris kamus yang nilai_kosong-nya lebih dari 0
kamus_kosong = kamus[kamus['nilai_kosong'] > 0]
kamus_kosong

,nama_kolom,tipe_data,nilai_unik,nilai_kosong,contoh_nilai,deskripsi,skala_pengukuran,kategori_data_pribadi,tindakan_penanganan
3,no_hp,float64,611,9,80004260813.0,None,None,None,None
26,skor_pascates,float64,64,34,67.0,None,None,None,None
27,tingkat_kepuasan,float64,28,18,5.0,None,None,None,None

### TODO C3 — isi kamus untuk lima kolom

Lengkapi tabel berikut. Deskripsi ditulis sebagai kalimat lengkap, bukan pengulangan nama kolom.

| Kolom | Deskripsi | Skala | Satuan |
|---|---|---|---|
| `lama_usaha_tahun` | Durasi waktu operasional usaha yang telah dijalankan oleh peserta hingga saat mendaftar|rasio|Tahun |
| `kehadiran_persen` |Persentase keikutsertaan peserta dalam seluruh sesi kegiatan pelatihan yang diselenggarakan|Rasio|Persen % |
| `skor_pascates` |Nilai evaluasi pemahaman materi yang diperoleh peserta setelah menyelesaikan pelatihan|interval|poin / skor |
| `kanal_pendaftaran` |Saluran atau media yang digunakan peserta untuk mendaftarkan diri pada program pelatihan|Nominal|Kategori (teks)|
| `jumlah_anak` |Total anak kandung atau tanggungan yang dimiliki oleh peserta pelatihan| Rasio|Orang / jiwa|

---
## Bagian D — Menandai data pribadi

| Kategori | Artinya |
|---|---|
| **pengenal langsung** | Sendirian sudah menunjuk ke satu orang |
| **quasi-identifier** | Sendirian aman, gabungannya menunjuk ke satu orang |
| **data spesifik** | Bocornya merugikan lebih berat (kesehatan, keuangan pribadi, data anak) |
| **bukan data pribadi** | Tidak menunjuk ke orang; inilah bahan analisis |

In [ ]:
# TODO D1 — susun tabel penandaan Anda sendiri
import pandas as pd

# 1. Definisikan dictionary PENANDAAN yang sesuai persis dengan df.columns
PENANDAAN = {
    # Pengenal langsung (Expected >= 5 kolom)
    'id_peserta': ('pengenal langsung', 'hash'),
    'nama_lengkap': ('pengenal langsung', 'hapus'),
    'nik_dummy': ('pengenal langsung', 'hapus'),
    'no_hp': ('pengenal langsung', 'hash'),
    'email': ('pengenal langsung', 'hash'),
    'alamat_jalan': ('pengenal langsung', 'hapus'),

    # Data spesifik (Expected >= 3 kolom: data anak, keuangan, kesehatan/disabilitas)
    'status_disabilitas': ('data spesifik', 'generalisasi'),
    'jumlah_anak': ('data spesifik', 'generalisasi'),
    'penghasilan_pribadi_bulanan': ('data spesifik', 'generalisasi'),
    'omzet_usaha_bulanan': ('data spesifik', 'generalisasi'),

    # Quasi-identifier (kombinasi demografi/lokasi)
    'tanggal_lahir': ('quasi-identifier', 'generalisasi'),
    'kelurahan': ('quasi-identifier', 'generalisasi'),
    'kecamatan': ('quasi-identifier', 'pertahankan'),
    'kota': ('quasi-identifier', 'pertahankan')
}

# 2. Bangun DataFrame 'tanda' untuk seluruh kolom df
data_tanda = []
for col in df.columns:
    if col in PENANDAAN:
        kat, tind = PENANDAAN[col]
    else:
        kat, tind = 'bukan data pribadi', 'pertahankan'
    data_tanda.append({'nama_kolom': col, 'kategori': kat, 'tindakan': tind})

tanda = pd.DataFrame(data_tanda)

# 3. Cetak jumlah kolom per kategori
print(tanda['kategori'].value_counts())
display(tanda)

kategori
bukan data pribadi    14
pengenal langsung      6
quasi-identifier       4
data spesifik          4
Name: count, dtype: int64

                     nama_kolom            kategori      tindakan
0                    id_peserta   pengenal langsung          hash
1                  nama_lengkap   pengenal langsung         hapus
2                     nik_dummy   pengenal langsung         hapus
3                         no_hp   pengenal langsung          hash
4                         email   pengenal langsung          hash
5                  alamat_jalan   pengenal langsung         hapus
6                     kelurahan    quasi-identifier  generalisasi
7                     kecamatan    quasi-identifier   pertahankan
8                          kota    quasi-identifier   pertahankan
9                 tanggal_lahir    quasi-identifier  generalisasi
10                jenis_kelamin  bukan data pribadi   pertahankan
11          pendidikan_terakhir  bukan data pribadi   pertahankan
12           status_disabilitas       data spesifik  generalisasi
13                  jumlah_anak       data spesifik  generalisasi
14  penghasilan_pribadi_bulanan       data spesifik  generalisasi
15                   nama_usaha  bukan data pribadi   pertahankan
16               kategori_usaha  bukan data pribadi   pertahankan
17                 produk_utama  bukan data pribadi   pertahankan
18             lama_usaha_tahun  bukan data pribadi   pertahankan
19              jumlah_karyawan  bukan data pribadi   pertahankan
20          omzet_usaha_bulanan       data spesifik  generalisasi
21        pernah_ikut_pelatihan  bukan data pribadi   pertahankan
22            kanal_pendaftaran  bukan data pribadi   pertahankan
23               tanggal_daftar  bukan data pribadi   pertahankan
24             kehadiran_persen  bukan data pribadi   pertahankan
25                  skor_prates  bukan data pribadi   pertahankan
26                skor_pascates  bukan data pribadi   pertahankan
27             tingkat_kepuasan  bukan data pribadi   pertahankan

### TODO D2 — pertanggungjawabkan tiga keputusan

Tiga kolom berikut sering diperdebatkan. Tulis keputusan Anda **beserta alasannya**.

| Kolom | Kategori pilihan Anda | Tindakan | Alasan |
|---|---|---|---|
| `nama_usaha` |pengenal langsung (atau quasi-identifier)|hapus atau hash|Jika dicari di mesin pencari (Google/Maps), nama usaha UMKM langsung mengarah pada profil pemilik dan lokasinya secara presisi|
| `omzet_usaha_bulanan` |data spesifik (atau bukan data pribadi)|generalisasi (atau pertahankan)|Merupakan data finansial sensitif; pada UMKM perorangan, batas keuangan usaha dan pribadi sering menyatu sehingga bocornya data merugikan pemilik|
| `id_peserta` |pengenal langsung|hash|Kita masih butuh membedakan tiap baris peserta (unique record) untuk analisis atau tracking tanpa perlu mengekspos identifier aslinya.|

> Petunjuk untuk `nama_usaha`: bayangkan seseorang mencari nama itu di mesin pencari.
> Petunjuk untuk `omzet_usaha_bulanan`: apakah ini data tentang **orang** atau tentang **usaha**?
> Petunjuk untuk `id_peserta`: apakah Anda masih perlu membedakan satu baris dari baris lain?

---
## Bagian E — Menerapkan tiga tindakan

In [ ]:
# TODO E1 — HAPUS
# Ambil daftar kolom yang bertindakan 'hapus' dari DataFrame tanda
kolom_hapus = tanda[tanda['tindakan'] == 'hapus']['nama_kolom'].tolist()

# Buat DataFrame baru 'aman'
aman = df.drop(columns=kolom_hapus)

print(f"Kolom yang dibuang : {len(kolom_hapus)} kolom ({kolom_hapus})")
print(f"Kolom yang tersisa : {aman.shape[1]} kolom")

Kolom yang dibuang : 3 kolom (['nama_lengkap', 'nik_dummy', 'alamat_jalan'])
Kolom yang tersisa : 25 kolom

In [ ]:
# TODO E2 — HASH
import hashlib
import numpy as np

GARAM = 'kunci-rahasia-tim-analisis-2026'

def samarkan(nilai, garam):
    if pd.isna(nilai):
        return np.nan
    # Gabungkan garam + string nilai, lalu hitung SHA-256 dan ambil 12 karakter pertama
    teks = str(garam) + str(nilai)
    return hashlib.sha256(teks.encode('utf-8')).hexdigest()[:12]

# Ambil kolom yang bertindakan 'hash' yang masih ada di DataFrame aman
kolom_hash = tanda[(tanda['tindakan'] == 'hash') & (tanda['nama_kolom'].isin(aman.columns))]['nama_kolom'].tolist()

# Terapkan fungsi samarkan
for col in kolom_hash:
    aman[col] = aman[col].apply(lambda x: samarkan(x, GARAM))

print("Kolom yang disamarkan (hash):", kolom_hash)
aman[kolom_hash].head()

Kolom yang disamarkan (hash): ['id_peserta', 'no_hp', 'email']

     id_peserta         no_hp         email
0  2c8af5d072aa  cf8b67f33ad2  bb9ccf21507e
1  7d09a063a4e7  aef0df5aa66d  65c553f4e2ea
2  570807cbfcab  9dad1eb62077  7c0398fdda8f
3  94c3a3e66dff  d8e24574f590  7be5d26cb99b
4  67c196b135b6  3ca3010dcd84  9e2c20befbcd

In [ ]:
# TODO E3 — buktikan hash bersifat konsisten dan tidak terbaca

# a. Hash dua kali nilai yang sama, tunjukkan hasilnya identik
nilai_a1 = samarkan("budi@example.com", GARAM)
nilai_a2 = samarkan("budi@example.com", GARAM)

print("--- Uji Konsistensi (Nilai Sama) ---")
print("Hash 1 :", nilai_a1)
print("Hash 2 :", nilai_a2)
print("Apakah identik?", nilai_a1 == nilai_a2)

# b. Hash dua nilai berbeda, tunjukkan hasilnya berbeda
nilai_b1 = samarkan("budi@example.com", GARAM)
nilai_b2 = samarkan("wati@example.com", GARAM)

print("\n--- Uji Nilai Berbeda ---")
print("Hash Budi :", nilai_b1)
print("Hash Wati :", nilai_b2)
print("Apakah berbeda?", nilai_b1 != nilai_b2)

--- Uji Konsistensi (Nilai Sama) ---
Hash 1 : 9192532f0406
Hash 2 : 9192532f0406
Apakah identik? True

--- Uji Nilai Berbeda ---
Hash Budi : 9192532f0406
Hash Wati : 1e17761746f3
Apakah berbeda? True

**Jawaban Anda:** kalau `GARAM` ikut ter-*commit* ke GitHub, apa yang masih terlindungi dan apa yang tidak?

_(Selama Garam nya belum terpecahkan maka data yang di hash akan tetap aman)_

In [ ]:
# TODO E4 — GENERALISASI
ACUAN = pd.Timestamp('2025-09-01')

# a. Hitung usia peserta pada tanggal acuan 1 September 2025
usia = (ACUAN - pd.to_datetime(df['tanggal_lahir'])).dt.days // 365.25

# b. Buat kolom 'kelompok_umur' dengan batas: <25, 25-34, 35-44, 45-54, 55+
bins = [-float('inf'), 24, 34, 44, 54, float('inf')]
labels = ['<25', '25-34', '35-44', '45-54', '55+']
aman['kelompok_umur'] = pd.cut(usia, bins=bins, labels=labels, right=True)

# c. Buat kolom kecamatan yang dirapikan (huruf kapital di awal / Title Case)
# dan pastikan kolom tanggal_lahir serta kelurahan dibuang dari 'aman'
aman['kecamatan'] = df['kecamatan'].str.strip().str.title()
aman = aman.drop(columns=['tanggal_lahir', 'kelurahan'], errors='ignore')

# Verifikasi hasil
print("Distribusi kelompok umur:")
print(aman['kelompok_umur'].value_counts())
print("\nJumlah nilai unik kecamatan:", aman['kecamatan'].nunique())

Distribusi kelompok umur:
kelompok_umur
35-44    267
25-34    153
45-54    108
<25       53
55+       39
Name: count, dtype: int64

Jumlah nilai unik kecamatan: 10

---
## Bagian F — Memeriksa sisa risiko

Menghapus nama belum tentu cukup. Untuk setiap kombinasi quasi-identifier, hitung berapa orang yang punya kombinasi sama. Nilai terkecil disebut **k**. Target kelas ini: **k ≥ 5**.

In [ ]:
# TODO F1 — tulis fungsi cek_k(data, kolom)
# Kembalikan Series berisi: k (grup terkecil), grup berisi 1 orang, total grup
def cek_k(data, kolom):
    ukuran_grup = data.groupby(kolom).size()

    k = ukuran_grup.min()
    grup_1_orang = (ukuran_grup == 1).sum()
    total_grup = len(ukuran_grup)

    return pd.Series({
        'k (grup terkecil)': k,
        'grup berisi 1 orang': grup_1_orang,
        'total grup': total_grup
    })

In [ ]:
# TODO F2 — ukur risiko SEBELUM penanganan
kolom_f2 = ['kelurahan', 'jenis_kelamin', 'pendidikan_terakhir', 'tanggal_lahir']
hasil_f2 = cek_k(df, kolom_f2)
print(hasil_f2)

k (grup terkecil)           0
grup berisi 1 orang       620
total grup             186576
dtype: int64

/tmp/ipykernel_3964/3761254163.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ukuran_grup = data.groupby(kolom).size()

**Jawaban Anda:** keempat kolom itu tidak memuat nama maupun nomor telepon. Jelaskan dalam dua kalimat mengapa hasilnya tetap berbahaya.

_(Meskipun tidak ada nama atau nomor telepon, kombinasi keempat atribut tersebut sangat unik sehingga setiap individu dapat dipisahkan secara tunggal ($k=1$). Data ini sangat mudah ditautkan (linkage attack) dengan basis data publik lain (seperti DPT Pemilu atau media sosial) untuk mengungkap identitas asli setiap peserta secara akurat. )_

In [ ]:
# TODO F3 — ukur risiko SESUDAH generalisasi
kolom_f3 = ['kecamatan', 'jenis_kelamin', 'pendidikan_terakhir', 'kelompok_umur']
hasil_f3 = cek_k(aman, kolom_f3)
print(hasil_f3)

k (grup terkecil)        0
grup berisi 1 orang    138
total grup             600
dtype: int64

/tmp/ipykernel_3964/3761254163.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ukuran_grup = data.groupby(kolom).size()

In [ ]:
# TODO F4 — TANTANGAN: capai k >= 5
aman_k5 = aman.copy()

# 1. Perlebar kelompok umur menjadi 3 kelompok besar
usia = (ACUAN - pd.to_datetime(df['tanggal_lahir'])).dt.days // 365.25
bins_lebar = [-float('inf'), 29, 44, float('inf')]
labels_lebar = ['<30', '30-44', '45+']
aman_k5['kelompok_umur_lebar'] = pd.cut(usia, bins=bins_lebar, labels=labels_lebar, right=True)

# 2. Generalisasi pendidikan menjadi 2 kelompok: 'Non-PT' dan 'PT'
peta_pendidikan = {
    'SD': 'Non-PT',
    'SMP': 'Non-PT',
    'SMA/SMK': 'Non-PT',
    'D3': 'PT',
    'S1': 'PT',
    'S2': 'PT'
}
aman_k5['pendidikan_ringkas'] = aman_k5['pendidikan_terakhir'].astype(str).map(peta_pendidikan)

# 3. Uji kombinasi kolom (hanya 3 quasi-identifier tanpa kecamatan)
kolom_f4 = ['jenis_kelamin', 'pendidikan_ringkas', 'kelompok_umur_lebar']

# Catatan: tambahkan observed=True agar tidak menghitung kombinasi kosong bernilai 0
hasil_f4 = aman_k5.groupby(kolom_f4, observed=True).size()

print("Distribusi per grup:")
print(hasil_f4)
print("\nk (grup terkecil):", hasil_f4.min())
print("grup berisi 1 orang:", (hasil_f4 == 1).sum())
print("total grup:", len(hasil_f4))

Distribusi per grup:
jenis_kelamin  pendidikan_ringkas  kelompok_umur_lebar
L              Non-PT              <30                     30
                                   30-44                   91
                                   45+                     48
               PT                  <30                     25
                                   30-44                   43
                                   45+                     21
P              Non-PT              <30                     39
                                   30-44                  128
                                   45+                     40
               PT                  <30                     37
                                   30-44                   80
                                   45+                     38
dtype: int64

k (grup terkecil): 21
grup berisi 1 orang: 0
total grup: 12

**Jawaban Anda:** tulis kombinasi yang Anda pilih, nilai k yang dicapai, dan informasi apa yang Anda korbankan untuk mencapainya.

_(Kombinasi yang dipilih: ['jenis_kelamin', 'pendidikan_ringkas', 'kelompok_umur_lebar']Nilai $k$ yang dicapai: 21 Informasi yang dikorbankan:Menghilangkan kolom lokasi (kecamatan) sepenuhnya dari daftar quasi-identifier.   Memperlebar rentang usia menjadi 3 kelompok saja (<30, 30-44, 45+).   Mengelompokkan pendidikan formal hanya ke dalam dua kategori besar (Non-PT dan PT))_

In [ ]:
# TODO F5 — sel kecil pada tabel agregat
import pandas as pd

# a. Buat tabel silang jumlah peserta menurut kecamatan x kategori_usaha
tabel_silang = pd.crosstab(aman['kecamatan'], aman['kategori_usaha'])
print("--- Tabel Silang (kecamatan x kategori_usaha) ---")
display(tabel_silang)

# b. Hitung berapa sel yang terisi tetapi berisi kurang dari 5 peserta (nilai 1 sampai 4)
kondisi_sel_kecil = (tabel_silang >= 1) & (tabel_silang < 5)
jumlah_sel_kecil = kondisi_sel_kecil.to_numpy().sum()

print(f"\nJumlah sel yang terisi tetapi berisi kurang dari 5 peserta (1-4): {jumlah_sel_kecil}")

--- Tabel Silang (kecamatan x kategori_usaha) ---

kategori_usaha  Fesyen  Jasa Digital  Kriya  Kuliner  Pertanian
kecamatan
Beji                14            10     15       42          6
Bojongsari           7             5      4       23          2
Cimanggis           16             8     15       44          7
Cinere              16            11      8       23          9
Cipayung             4             6      5       10          1
Limo                10             4     10       15          4
Pancoran Mas        25            12     19       31         12
Sawangan             5             3      3       10          2
Sukmajaya           22            14     11       36         12
Tapos               11             5     11       16          6

Jumlah sel yang terisi tetapi berisi kurang dari 5 peserta (1-4): 9